{
    "id": 129629,
    "name": "CVE-2019-16249",
    "cwe": "CWE-125",
    "modified": "2019-12-03T18:01:55",
    "published": "2019-09-11T21:15:14",
    "status": "Analyzed",
    "summary": "OpenCV 4.1.1 has an out-of-bounds read in hal_baseline::v_load in core/hal/intrin_sse.hpp when called from computeSSDMeanNorm in modules/video/src/dis_flow.cpp.",
    "cvss3": {
        "cvss": 5.3,
        "exploitability_score": 3.9,
        "impact_score": 1.4,
        "vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N"
    },
    "cvss2": {
        "exploitability_score": 10.0,
        "impact_score": 2.9,
        "cvss": 5.0,
        "vector": "AV:N/AC:L/Au:N/C:P/I:N/A:N"
    },
    "cpes": [
        {
            "id": 323869
        }
    ]
}