{
    "id": 175874,
    "name": "CVE-2021-45102",
    "cwe": "CWE-863",
    "modified": "2021-12-22T18:51:33",
    "published": "2021-12-16T04:15:08",
    "status": "Analyzed",
    "summary": "An issue was discovered in HTCondor 9.0.x before 9.0.4 and 9.1.x before 9.1.2. When authenticating to an HTCondor daemon using a SciToken, a user may be granted authorizations beyond what the token should allow.",
    "cvss3": {
        "cvss": 8.8,
        "exploitability_score": 2.8,
        "impact_score": 5.9,
        "vector": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H"
    },
    "cvss2": {
        "exploitability_score": 8.0,
        "impact_score": 6.4,
        "cvss": 6.5,
        "vector": "AV:N/AC:L/Au:S/C:P/I:P/A:P"
    },
    "cpes": [
        {
            "id": 747486
        },
        {
            "id": 747487
        },
        {
            "id": 747488
        },
        {
            "id": 747489
        }
    ]
}