{
    "id": 254602,
    "name": "CVE-2024-38355",
    "cwe": "Unknown",
    "modified": "2024-06-20T10:43:25",
    "published": "2024-06-19T18:15:11",
    "status": "Awaiting Analysis",
    "summary": "Socket.IO is an open source, real-time, bidirectional, event-based, communication framework. A specially crafted Socket.IO packet can trigger an uncaught exception on the Socket.IO server, thus killing the Node.js process. This issue is fixed by commit `15af22fc22` which has been included in `socket.io@4.6.2` (released in May 2023). The fix was backported in the 2.x branch as well with commit `d30630ba10`. Users are advised to upgrade. Users unable to upgrade may attach a listener for the \"error\" event to catch these errors.\n",
    "cvss3": {
        "cvss": 7.3,
        "exploitability_score": 3.9,
        "impact_score": 3.4,
        "vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:L/A:L"
    },
    "cvss2": null,
    "cpes": []
}