{
    "id": 193854,
    "name": "CVE-2022-37428",
    "cwe": "CWE-459",
    "modified": "2023-11-07T02:49:48",
    "published": "2022-08-23T15:15:15",
    "status": "Modified",
    "summary": "PowerDNS Recursor up to and including 4.5.9, 4.6.2 and 4.7.1, when protobuf logging is enabled, has Improper Cleanup upon a Thrown Exception, leading to a denial of service (daemon crash) via a DNS query that leads to an answer with specific properties.",
    "cvss3": {
        "cvss": 6.5,
        "exploitability_score": 2.8,
        "impact_score": 3.6,
        "vector": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H"
    },
    "cvss2": null,
    "cpes": [
        {
            "id": 867883
        },
        {
            "id": 868928
        },
        {
            "id": 868929
        },
        {
            "id": 868930
        },
        {
            "id": 868931
        },
        {
            "id": 868932
        },
        {
            "id": 868933
        },
        {
            "id": 868934
        },
        {
            "id": 868935
        },
        {
            "id": 868936
        },
        {
            "id": 868937
        },
        {
            "id": 868938
        },
        {
            "id": 868939
        },
        {
            "id": 868940
        },
        {
            "id": 868941
        },
        {
            "id": 868942
        },
        {
            "id": 868943
        },
        {
            "id": 868944
        },
        {
            "id": 868945
        },
        {
            "id": 868946
        },
        {
            "id": 868947
        },
        {
            "id": 868948
        },
        {
            "id": 868949
        },
        {
            "id": 929528
        },
        {
            "id": 929529
        },
        {
            "id": 929530
        },
        {
            "id": 929531
        },
        {
            "id": 929533
        },
        {
            "id": 929535
        }
    ]
}