{
    "id": 101102,
    "name": "CVE-2018-6892",
    "cwe": "CWE-119",
    "modified": "2020-10-05T23:15:12",
    "published": "2018-02-11T17:29:00",
    "status": "Modified",
    "summary": "An issue was discovered in CloudMe before 1.11.0. An unauthenticated remote attacker that can connect to the \"CloudMe Sync\" client application listening on port 8888 can send a malicious payload causing a buffer overflow condition. This will result in an attacker controlling the program's execution flow and allowing arbitrary code execution.",
    "cvss3": null,
    "cvss2": null,
    "cpes": [
        {
            "id": 335152
        }
    ]
}