{
    "id": 154288,
    "name": "CVE-2020-24340",
    "cwe": "CWE-125",
    "modified": "2020-12-14T20:29:11",
    "published": "2020-12-11T22:15:14",
    "status": "Analyzed",
    "summary": "An issue was discovered in picoTCP and picoTCP-NG through 1.7.0. The code that processes DNS responses in pico_mdns_handle_data_as_answers_generic() in pico_mdns.c does not check whether the number of answers/responses specified in a DNS packet header corresponds to the response data available in the packet, leading to an out-of-bounds read, invalid pointer dereference, and Denial-of-Service.",
    "cvss3": {
        "cvss": 7.5,
        "exploitability_score": 3.9,
        "impact_score": 3.6,
        "vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H"
    },
    "cvss2": {
        "exploitability_score": 10.0,
        "impact_score": 2.9,
        "cvss": 5.0,
        "vector": "AV:N/AC:L/Au:N/C:N/I:N/A:P"
    },
    "cpes": [
        {
            "id": 434263
        },
        {
            "id": 434264
        },
        {
            "id": 434265
        },
        {
            "id": 434266
        },
        {
            "id": 434267
        },
        {
            "id": 434268
        },
        {
            "id": 434269
        },
        {
            "id": 434270
        },
        {
            "id": 434271
        },
        {
            "id": 434272
        },
        {
            "id": 434273
        },
        {
            "id": 434274
        },
        {
            "id": 434275
        },
        {
            "id": 434276
        },
        {
            "id": 434277
        },
        {
            "id": 434278
        },
        {
            "id": 637111
        },
        {
            "id": 637112
        }
    ]
}