{
    "id": 94788,
    "name": "CVE-2017-14503",
    "cwe": "CWE-125",
    "modified": "2018-12-28T15:29:01",
    "published": "2017-09-17T16:29:00",
    "status": "Modified",
    "summary": "libarchive 3.3.2 suffers from an out-of-bounds read within lha_read_data_none() in archive_read_support_format_lha.c when extracting a specially crafted lha archive, related to lha_crc16.",
    "cvss3": null,
    "cvss2": null,
    "cpes": [
        {
            "id": 209980
        }
    ]
}