{
    "id": 134832,
    "name": "CVE-2014-8650",
    "cwe": "CWE-287",
    "modified": "2019-12-19T17:08:32",
    "published": "2019-12-15T21:15:12",
    "status": "Analyzed",
    "summary": "python-requests-Kerberos through 0.5 does not handle mutual authentication",
    "cvss3": {
        "cvss": 9.8,
        "exploitability_score": 3.9,
        "impact_score": 5.9,
        "vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H"
    },
    "cvss2": {
        "exploitability_score": 10.0,
        "impact_score": 6.4,
        "cvss": 7.5,
        "vector": "AV:N/AC:L/Au:N/C:P/I:P/A:P"
    },
    "cpes": [
        {
            "id": 109409
        },
        {
            "id": 124875
        },
        {
            "id": 469463
        },
        {
            "id": 469464
        },
        {
            "id": 469465
        },
        {
            "id": 469466
        },
        {
            "id": 469467
        },
        {
            "id": 587080
        }
    ]
}